#!/usr/bin/env python3

import os
from subprocess import call

celery_queue=os.environ.get("CELERY_QUEUE","celery")
log_level=os.environ.get("LOG_LEVEL","INFO")

call(["/app/venv/bin/celery", "worker", "-Q", celery_queue, "-l", log_level,"-n",f"{celery_queue}@%h"])
